services:
  board:
    image: ghcr.io/zhini-co-in/board:1.0.26090801
    container_name: board-app
    restart: always
    ports:
      - "4000:8080"
    networks:
      - app-network
    environment:
      - MONGO_URL=mongodb://dev_db_user:7cBNvaJmiJdasAgJ@ac-epobvi7-shard-00-00.dhu5rvl.mongodb.net:27017,ac-epobvi7-shard-00-01.dhu5rvl.mongodb.net:27017,ac-epobvi7-shard-00-02.dhu5rvl.mongodb.net:27017/board?ssl=true&replicaSet=atlas-je3c22-shard-0&authSource=admin&appName=kondaas
      - ROOT_URL=http://localhost:4000
      - PORT=8080
      - WITH_API=true

networks:
  app-network:
    external: true